server:
  port: 4001
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/springcloud_sell
    username: root
    password: root
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat
      pool-prepared-statements: false
      filter:
        slf4j:
          connection-logger-name: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka/
mybatis:
  type-aliases-package: com.rdkl.xtbj.domain
  configuration:
  # \u8F6C\u9A7C\u5CF0\u547D\u540D
    map-underscore-to-camel-case: true
logging:
  level:
    com.rdkl.product.mapper: debug
  env:
    dev
